### PR TITLE
fix: show correct new line character

### PR DESCRIPTION
**Pull request by ji2k**

### CODE REVIEW

**Comment by samipak458** [comment]
Hi @tzii,
Thanks for creating a PR. Explain what changes you made and attach screenshots.

**Comment by ji2k** [comment]
I added `white-space: pre-line` css attribute 
image
image

**Comment by samipak458** [comment]
@tzii What if we add text, does it show space like in its shows in number?

**Comment by ji2k** [comment]
I don't know what's your point, but in screen shot, they are all characters.

**Comment by samipak458** [comment]
Does it show the same space in words? Can you add word and add the screenshot?

**Comment by ji2k** [comment]
image
image

**Comment by ji2k** [comment]
image
Here's input.

**Comment by samipak458** [comment]
Good job @tzii

**Pull request merged**
