### PR TITLE
Contributor Section added

### PR DESCRIPTION
**Pull request by Sohaibkamran-25**
I have added contributor section

### CODE REVIEW

**Comment by Sohaibkamran-25** [comment]
Kindly review my pull request @samipak458

**Comment by samipak458** [comment]
Kindly add Screenshot of your changes @Sohaibkamran-25

**Comment by Sohaibkamran-25** [comment]
image
This is the screenshot of changes i made.

**Comment by samipak458** [comment]
Good job @Sohaibkamran-25 👍

**Pull request merged**
