### PR TITLE
Migrate to tailwindcss

### LINKED ISSUE #16: Refactor to TailwindCSS
## Description:
I want to refactor this project's styling to tailwind css.

 Can I be assigned this issue under hacktoberfest2022?

### PR DESCRIPTION
**Pull request by rajdip-b**
Fixes #16 

Side note, I left the toggle button in header unstyled as I would change it in another PR

### CODE REVIEW

**Comment by samipak458** [comment]
Kindly add short video of your changes @rajdip-b

**Comment by rajdip-b** [comment]
> Kindly add short video of your changes @rajdip-b

Hey, I just changed css to tailwind. Everything is exactly the same. Would screenshots do?

**Comment by rajdip-b** [comment]
[Screencast from 23-10-22 06:21:07 PM IST.webm](https://user-images.githubusercontent.com/83924254/197393167-a3a7e9cb-a4a4-4f02-94dc-2d6bc8467384.webm)
@samipak458

**Comment by samipak458** [comment]
Toggle button not looks good.

**Comment by rajdip-b** [comment]
> Toggle button not looks good.

Yeah like i mentioned i would be fixing it in #17

**Comment by rajdip-b** [comment]
@samipak458 hey can i get this PR merged?

**Comment by samipak458** [comment]
@rajdip-b I like the changes you made, can you write about it that how do you install tailwind in Readme it would be good for beginners to understand.

**Comment by samipak458** [comment]
You can also made separate PR for this but I need the step by step guidelines so that it will help beginner.

**Comment by rajdip-b** [comment]
> 

There is no additional efforts required by any programmer to set up tailwind over again. npm install would do everything.

**Pull request merged**
