### PR TITLE
Dark mode enabled

### PR DESCRIPTION
**Pull request by Rohitsuper69**

### CODE REVIEW

**Comment by samipak458** [comment]
Hi @Rohitsuper69,
Thanks for creating a PR. Dark mode is already added,  explain what do you do And attach screen shots.

**Comment by Rohitsuper69** [comment]
> 
final
final2
ok so I changed it into a toggle button and changed the UI of dark mode also

**Comment by samipak458** [comment]
@Rohitsuper69 why do you deleted? It is valid PR.

**Comment by Rohitsuper69** [comment]
sorry Iam putting it back

**Pull request closed without merging**
